### ISSUE TITLE
Avoid warnings from nmap

### ISSUE THREAD

**Issue by nobanzai** [modernistik/Nmap-Parser#14]
Hi,

when running

`my( $nmapCmd ) = "/usr/bin/nmap";`
`my( $nmap ) = new Nmap::Parser;`
`$nmap->parsescan( $nmapCmd, '-n -sn', ( "192.168.1.1/24" ) );`

I get lots of warning like this one:

`adjust_timeouts2: packet supposedly had rtt of -102238 microseconds.  Ignoring time.`

Reason seems to be "-v -v -v" in the call to nmap in Parser.pm.
Is there anything I can do against these warnings?

Thx and bye.
Michael.

**Comment by apersaud** [comment]
Unfotunately it may not be possible as using those switches provides additional information in the XML as far as I remember.
